# name: First GitHub Action

# on:
#   push:
#     branches:
#       - main

# jobs:
#   demo-job:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Print Hello
#         run: echo "Hello aditya from GitHub Actions"




# name: Jobs and Steps Demo

# on:
#   push:
#     branches:
#       - main

# jobs:
#   demo-job:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Step 1 – Check OS
#         run: |
#           uname -a
#           whoami

#       - name: Step 2 – Create a file
#         run: |
#           echo "This file was created in Step 2" > demo.txt
#           ls -l

#       - name: Step 3 – Read the file
#         run: |
#           cat demo.txt




# name: Checkout Demo

# on:
#   push:
#     branches:
#       - main

# jobs:
#   demo-job:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: List repository files
#         run: |
#           ls -l



# name: Environment Variables Demo

# on:
#   push:
#     branches:
#       - main

# env:
#   APP_NAME: github-actions-demo

# jobs:
#   demo-job:
#     runs-on: ubuntu-latest

#     env:
#       JOB_ENV: production

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Use workflow and job env
#         run: |
#           echo "App Name: $APP_NAME"
#           echo "Job Environment: $JOB_ENV"

#       - name: Step level env
#         env:
#           STEP_ENV: step-only
#         run: |
#           echo "Step Env: $STEP_ENV"




# name: Secrets Demo

# on:
#   push:
#     branches:
#       - main

# jobs:
#   secret-job:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Use secret safely
#         run: |
#           echo "Secret is available"
#           echo "Length of secret: ${#MY_SECRET}"
#         env:
#           MY_SECRET: ${{ secrets.MY_SECRET }}







name: Failure Demo

on:
  push:
    branches:
      - main

jobs:
  failure-job:
    runs-on: ubuntu-latest

    steps:
      - name: Successful step
        run: |
          echo "This step succeeds"

      - name: Intentional failure
        run: |
          echo "Failing now"
          exit 1

      - name: This will NOT run
        run: |
          echo "You will never see this"

